version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-weather-app
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: weather_app_database
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3308:3306"
    volumes:
      - ./data:/var/lib/mysql

  data-importer:
    image: mysql:latest
    container_name: data-importer
    command: bash -c "sleep 10 && mysql -hmysql -uroot -p123456 weather_app_database < C:\Users\Laptop T&T\Documents\dumps\weatherdatabase.sql"
    volumes:
      - ./data:/data
    depends_on:
      - mysql
